// @generated by openapi-codegen from specs/sabre-booking/spec.openapi.yaml
// Do not edit by hand.

use ::serde::{Deserialize, Serialize};
use ::struct_patch::Patch;
use super::super::refund_tickets::request::*;
use super::super::shared::common::*;
use super::super::shared::enums::*;
use super::super::shared::response::*;

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);

    impl ::std::error::Error for ConversionError {}

    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }

    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }

    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }

    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}

/// Contains voided ticket information.
#[serde_with::skip_serializing_none]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Patch)]
#[serde(rename_all = "camelCase")]
#[patch(attribute(serde_with::skip_serializing_none))]
#[patch(attribute(derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)))]
#[patch(attribute(serde(default, rename_all = "camelCase")))]
#[cfg_attr(feature = "schemars", patch(attribute(derive(schemars::JsonSchema))))]
pub struct RefundTicketsResponse {
    /// Lists detailed error information. This array is not displayed in successful responses.
    pub errors: ::std::option::Option<::std::vec::Vec<Error>>,
    /// Lists all successfully refunded tickets.
    pub refunded_tickets: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    #[patch(name = "Option<RefundTicketsRequestPatch>")]
    pub request: ::std::option::Option<RefundTicketsRequest>,
    /// Lists information about cancellation eligibility and refundable amounts per ticket in the
    /// order of the request.
    pub tickets: ::std::option::Option<::std::vec::Vec<Ticket>>,
    /// Provides the exact point in time when the response was generated. The timestamp is expressed
    /// in UTC and presented in the YYYY-MM-DDTHH:MM:SSZ format.
    pub timestamp: ::std::option::Option<::std::string::String>,
}
