// @generated by openapi-codegen from specs/sabre-booking/spec.openapi.yaml
// Do not edit by hand.

pub mod cancel_booking;
pub mod check_tickets;
pub mod create_booking;
pub mod fulfill_tickets;
pub mod get_booking;
pub mod modify_booking;
pub mod refund_tickets;
pub mod shared;
pub mod void_tickets;
/// Generated API client: `client::Client`, its builder, the
/// `auth` providers, and the `support` error/helper surface.
pub mod client;
/// User-owned extensions; scaffolded once, never regenerated.
pub mod ext;
