// @generated by openapi-codegen from specs/petstore.yaml
// Do not edit by hand.

use ::serde::{Deserialize, Serialize};
use ::struct_patch::Patch;
use super::super::shared::common::*;
use super::super::shared::enums::*;
use super::super::shared::request::*;
pub use super::super::support::error;

///`CreatePetRequest`
#[serde_with::skip_serializing_none]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Patch)]
#[serde(rename_all = "camelCase")]
#[patch(attribute(serde_with::skip_serializing_none))]
#[patch(attribute(derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)))]
#[patch(attribute(serde(default, rename_all = "camelCase")))]
#[cfg_attr(feature = "schemars", patch(attribute(derive(schemars::JsonSchema))))]
pub struct CreatePetRequest {
    #[patch(name = "Option<CategoryPatch>")]
    pub category: ::std::option::Option<Category>,
    pub idempotency_key: ::std::option::Option<::std::string::String>,
    pub name: ::std::string::String,
    pub photo_urls: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    pub received_from: ::std::option::Option<::std::string::String>,
    pub wants_newsletter: ::std::option::Option<bool>,
}
