//! The optional / per-type `struct_patch` configuration
//! (docs/MIGRATION.md D13): the `[style] patch` baseline, per-type
//! `[types."Name"] patch` overrides, cross-type pruning of
//! `#[patch(name = ...)]` annotations, and the hard errors for
//! unmatched or contradictory selectors. The typify engine is not
//! affected — its Patch behavior stays the fork's all-or-nothing
//! unconditional-derive mechanism.

use openapi_codegen::{Generator, StyleConfig};

/// Write `document` (an OpenAPI JSON document) to a temp spec file and
/// return an IR-engine generator for it.
fn generator_for(name: &str, document: serde_json::Value) -> Generator {
    let dir = std::path::PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join("patch_config");
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join(format!("{name}.json"));
    std::fs::write(&path, serde_json::to_string_pretty(&document).unwrap()).unwrap();
    Generator::new(path)
        .profile(openapi_codegen::StyleProfile::ApiClient)
        
}

/// A small spec with cross-references: `Order` holds `Option<Category>`
/// and `Option<Payment>` fields (both deep-patch candidates), plus a
/// string enum to pin the non-struct rules.
fn order_spec() -> serde_json::Value {
    serde_json::json!({
        "openapi": "3.0.0",
        "info": { "title": "t", "version": "1" },
        "paths": {},
        "components": { "schemas": {
            "Order": {
                "type": "object",
                "properties": {
                    "category": { "$ref": "#/components/schemas/Category" },
                    "payment": { "$ref": "#/components/schemas/Payment" }
                }
            },
            "Category": {
                "type": "object",
                "properties": { "name": { "type": "string" } }
            },
            "Payment": {
                "type": "object",
                "properties": { "method": { "type": "string" } }
            },
            "Status": { "type": "string", "enum": ["open", "closed"] }
        } }
    })
}

/// Drop the `// @generated by openapi-codegen from <path>` header — the
/// spec path varies per test (and contains this file's temp directory
/// name), so assertions run on the body only.
fn body(out: &str) -> &str {
    out.split_once("\n\n").expect("generated header").1
}

/// The output slice for one emitted item: from its `///`Name`` doc line
/// to the next item's doc line (items carry no spec descriptions here).
fn item_block<'a>(out: &'a str, name: &str) -> &'a str {
    let marker = format!("///`{name}`");
    let start = out
        .find(&marker)
        .unwrap_or_else(|| panic!("no item {name} in:\n{out}"));
    let rest = &out[start + marker.len()..];
    let end = rest
        .find("///`")
        .map(|offset| start + marker.len() + offset)
        .unwrap_or(out.len());
    &out[start..end]
}

#[test]
fn patch_off_globally_strips_all_patch_machinery() {
    let generated = generator_for("global_off", order_spec())
        .style(|style| style.patch = false)
        .generate_to_string()
        .unwrap();
    let out = body(&generated);

    // No derive, no `#[patch(attribute(...))]` lines, no cfg-gated
    // schemars patch attr, no `#[patch(name = ...)]` annotations, and no
    // `use ::struct_patch::Patch;` import — "Patch"/"patch" vanish.
    assert!(!out.contains("Patch"), "no Patch anywhere:\n{out}");
    assert!(!out.contains("patch"), "no patch attrs anywhere:\n{out}");

    // Non-patch machinery is untouched.
    assert!(
        out.contains("#[serde_with::skip_serializing_none]"),
        "non-patch attrs survive:\n{out}",
    );
    assert!(
        out.contains("#[cfg_attr(feature = \"schemars\", derive(schemars::JsonSchema))]"),
        "non-patch conditional derives survive:\n{out}",
    );
    assert!(
        out.contains("#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]"),
        "derive list keeps everything but Patch:\n{out}",
    );
    assert!(
        out.contains("use ::serde::{Deserialize, Serialize};"),
        "serde import survives:\n{out}",
    );
}

#[test]
fn patch_off_for_one_type_prunes_annotations_on_referencing_fields() {
    let out = generator_for("one_type_off", order_spec())
        .style(|style| {
            style.types.entry("Category".to_string()).or_default().patch = Some(false);
        })
        .generate_to_string()
        .unwrap();

    // Category itself: no Patch derive, no patch attrs; everything else
    // (serde surface, cfg-gated schemars derive) intact.
    let category = item_block(&out, "Category");
    assert!(!category.contains("Patch"), "Category sheds Patch:\n{category}");
    assert!(!category.contains("#[patch"), "Category sheds patch attrs:\n{category}");
    assert!(
        category.contains("#[cfg_attr(feature = \"schemars\", derive(schemars::JsonSchema))]"),
        "Category keeps the plain schemars derive:\n{category}",
    );

    // Order stays fully patchable...
    let order = item_block(&out, "Order");
    assert!(
        order.contains("Serialize, Deserialize, Patch)]"),
        "Order keeps the Patch derive:\n{order}",
    );
    assert!(
        order.contains("#[patch(attribute(serde_with::skip_serializing_none))]"),
        "Order keeps the patch attribute block:\n{order}",
    );
    // ...but its field referencing the unpatchable Category loses the
    // deep-patch annotation (CategoryPatch will not exist), while the
    // field referencing the still-patchable Payment keeps it.
    assert!(
        !out.contains("CategoryPatch"),
        "no reference to the nonexistent CategoryPatch:\n{out}",
    );
    assert!(
        order.contains("#[patch(name = \"Option<PaymentPatch>\")]"),
        "Order.payment still deep-patches:\n{order}",
    );

    // The struct_patch import stays: other types still derive Patch.
    assert!(out.contains("use ::struct_patch::Patch;"), "{out}");
}

#[test]
fn reenable_one_type_under_global_off() {
    let out = generator_for("reenable", order_spec())
        .style(|style| {
            style.patch = false;
            style.types.entry("Order".to_string()).or_default().patch = Some(true);
        })
        .generate_to_string()
        .unwrap();

    // Order carries the full machinery again...
    let order = item_block(&out, "Order");
    assert!(
        order.contains("Serialize, Deserialize, Patch)]"),
        "Order re-enabled:\n{order}",
    );
    assert!(
        order.contains("#[patch(attribute(serde(default, rename_all = \"camelCase\")))]"),
        "Order keeps patch attrs:\n{order}",
    );
    assert!(
        order.contains("feature = \"schemars\", patch(attribute(derive(schemars::JsonSchema)))"),
        "Order keeps the cfg-gated patch attr:\n{order}",
    );
    // ...except deep-patch annotations: both referenced types are
    // unpatchable, so their companions won't exist.
    assert!(!out.contains("patch(name"), "annotations pruned:\n{out}");

    // The other structs stay patch-free.
    let category = item_block(&out, "Category");
    assert!(!category.contains("Patch"), "{category}");
    let payment = item_block(&out, "Payment");
    assert!(!payment.contains("Patch"), "{payment}");

    // Something is patchable, so the import stays.
    assert!(out.contains("use ::struct_patch::Patch;"), "{out}");
}

#[test]
fn unmatched_patch_selector_errors() {
    let error = format!(
        "{:#}",
        generator_for("unmatched", order_spec())
            .style(|style| {
                style.types.entry("Nope".to_string()).or_default().patch = Some(false);
            })
            .generate_to_string()
            .unwrap_err(),
    );
    assert!(error.contains("Nope"), "{error}");
    assert!(error.contains("matched nothing"), "{error}");
}

#[test]
fn patch_override_on_non_struct_errors() {
    let error = format!(
        "{:#}",
        generator_for("enum_target", order_spec())
            .style(|style| {
                style.types.entry("Status".to_string()).or_default().patch = Some(false);
            })
            .generate_to_string()
            .unwrap_err(),
    );
    assert!(error.contains("Status"), "{error}");
    assert!(error.contains("not a struct"), "{error}");
}

#[test]
fn forced_deep_patch_into_unpatchable_type_errors() {
    let error = format!(
        "{:#}",
        generator_for("forced_inner", order_spec())
            .style(|style| {
                style.types.entry("Category".to_string()).or_default().patch = Some(false);
                style
                    .fields
                    .entry("Order.category".to_string())
                    .or_default()
                    .deep_patch = Some(true);
            })
            .generate_to_string()
            .unwrap_err(),
    );
    assert!(error.contains("CategoryPatch"), "{error}");
    assert!(error.contains("deep-patch = true"), "{error}");
}

#[test]
fn forced_deep_patch_on_unpatchable_owner_errors() {
    let error = format!(
        "{:#}",
        generator_for("forced_owner", order_spec())
            .style(|style| {
                style.types.entry("Order".to_string()).or_default().patch = Some(false);
                style
                    .fields
                    .entry("Order.category".to_string())
                    .or_default()
                    .deep_patch = Some(true);
            })
            .generate_to_string()
            .unwrap_err(),
    );
    assert!(error.contains("`Order` has patch disabled"), "{error}");
    assert!(error.contains("owning struct's `Patch` derive"), "{error}");
}

#[test]
fn codegen_toml_and_style_hook_are_isomorphic() {
    let toml = r#"
        profile = "api-client"

        [style]
        patch = false

        [types."Order"]
        patch = true
    "#;

    // The parsed config carries both settings.
    let config = StyleConfig::from_toml_str(toml, StyleConfig::api_client()).unwrap();
    assert!(!config.patch);
    assert_eq!(config.types["Order"].patch, Some(true));

    let dir = std::path::PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join("patch_config");
    std::fs::create_dir_all(&dir).unwrap();
    let config_path = dir.join("iso.toml");
    std::fs::write(&config_path, toml).unwrap();

    let via_toml = generator_for("iso_toml", order_spec())
        .config_file(config_path)
        .generate_to_string()
        .unwrap();
    let via_hook = generator_for("iso_hook", order_spec())
        .style(|style| {
            style.patch = false;
            style.types.entry("Order".to_string()).or_default().patch = Some(true);
        })
        .generate_to_string()
        .unwrap();
    // Bodies must match byte-for-byte (headers name different temp spec
    // paths).
    assert_eq!(
        body(&via_toml),
        body(&via_hook),
        "config file and style() hook diverge",
    );
}
