// @generated by openapi-codegen from specs/sabre-booking/spec.openapi.yaml
// Do not edit by hand.

use ::serde::{Deserialize, Serialize};
use ::struct_patch::Patch;
use super::super::check_tickets::request::*;
use super::super::shared::common::*;
use super::super::shared::enums::*;
use super::super::shared::response::*;

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);

    impl ::std::error::Error for ConversionError {}

    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }

    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }

    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }

    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}

/// Contains detailed information about a specific cancellation option for a NDC Order item.
#[serde_with::skip_serializing_none]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Patch)]
#[serde(rename_all = "camelCase")]
#[patch(attribute(serde_with::skip_serializing_none))]
#[patch(attribute(derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)))]
#[patch(attribute(serde(default, rename_all = "camelCase")))]
#[cfg_attr(feature = "schemars", patch(attribute(derive(schemars::JsonSchema))))]
pub struct CancelOffer {
    /// The expiration date of a cancel offer.
    pub offer_expiration_date: ::std::option::Option<::std::string::String>,
    /// The expiration time of a cancel offer in UTC.
    pub offer_expiration_time: ::std::option::Option<::std::string::String>,
    /// Offer ID referencing the cancel option for a NDC order. This ID must be applied when
    /// cancelling an order to receive a refund or void.
    pub offer_item_id: ::std::option::Option<::std::string::String>,
    pub offer_type: ::std::option::Option<CancelOfferTypeEnum>,
    #[patch(name = "Option<TotalValuesPatch>")]
    pub refund_totals: ::std::option::Option<TotalValues>,
}

/// Identifies the offer type of the cancel option.
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum CancelOfferTypeEnum {
    #[serde(rename = "VOID")]
    Void,
    #[serde(rename = "REFUND")]
    Refund,
}

impl ::std::fmt::Display for CancelOfferTypeEnum {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Void => f.write_str("VOID"),
            Self::Refund => f.write_str("REFUND"),
        }
    }
}

impl ::std::str::FromStr for CancelOfferTypeEnum {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "VOID" => Ok(Self::Void),
            "REFUND" => Ok(Self::Refund),
            _ => Err("invalid value".into()),
        }
    }
}

impl ::std::convert::TryFrom<&str> for CancelOfferTypeEnum {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}

impl ::std::convert::TryFrom<&::std::string::String> for CancelOfferTypeEnum {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}

impl ::std::convert::TryFrom<::std::string::String> for CancelOfferTypeEnum {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}

impl ::std::default::Default for CancelOfferTypeEnum {
    fn default() -> Self {
        Self::Void
    }
}

/// Contains information about cancellation eligibility and refundable amounts per ticket.
#[serde_with::skip_serializing_none]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Patch)]
#[serde(rename_all = "camelCase")]
#[patch(attribute(serde_with::skip_serializing_none))]
#[patch(attribute(derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)))]
#[patch(attribute(serde(default, rename_all = "camelCase")))]
#[cfg_attr(feature = "schemars", patch(attribute(derive(schemars::JsonSchema))))]
pub struct CheckTicketsResponse {
    /// Lists information about cancellation options for NDC Orders.
    pub cancel_offers: ::std::option::Option<::std::vec::Vec<CancelOffer>>,
    /// Lists detailed error information. This array is not displayed in successful responses.
    pub errors: ::std::option::Option<::std::vec::Vec<Error>>,
    /// Lists information about flight refund options.
    pub flight_refunds: ::std::option::Option<::std::vec::Vec<FlightRefund>>,
    #[patch(name = "Option<CheckTicketsRequestPatch>")]
    pub request: ::std::option::Option<CheckTicketsRequest>,
    /// Lists information about cancellation eligibility and refundable amounts per ticket in the
    /// order of the request.
    pub tickets: ::std::option::Option<::std::vec::Vec<CheckedTicket>>,
    /// Provides the exact point in time when the response was generated. The timestamp is expressed
    /// in UTC and presented in the YYYY-MM-DDTHH:MM:SSZ format.
    pub timestamp: ::std::option::Option<::std::string::String>,
}

/// Contains detailed information about cancellation eligibility, refundable amounts, and
/// exchangeability data for a single ticket.
#[serde_with::skip_serializing_none]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Patch)]
#[serde(rename_all = "camelCase")]
#[patch(attribute(serde_with::skip_serializing_none))]
#[patch(attribute(derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)))]
#[patch(attribute(serde(default, rename_all = "camelCase")))]
#[cfg_attr(feature = "schemars", patch(attribute(derive(schemars::JsonSchema))))]
pub struct CheckedTicket {
    #[serde(flatten)]
    pub ticket: Ticket,
    #[patch(name = "Option<RefundFeePatch>")]
    pub refund_fee: ::std::option::Option<RefundFee>,
}

/// Contains structured details about the cancellation fee applied during an automated refund
/// process. Includes the fee amount, currency, and any applicable taxes.
#[serde_with::skip_serializing_none]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Patch)]
#[serde(rename_all = "camelCase")]
#[patch(attribute(serde_with::skip_serializing_none))]
#[patch(attribute(derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)))]
#[patch(attribute(serde(default, rename_all = "camelCase")))]
#[cfg_attr(feature = "schemars", patch(attribute(derive(schemars::JsonSchema))))]
pub struct RefundFee {
    /// The monetary value of the cancellation fee. This amount represents the cost charged for
    /// canceling a ticket and may be subject to additional taxes listed in the `taxes` array.
    pub amount: ::std::option::Option<::std::string::String>,
    /// The three-letter ISO 4217 currency code.
    pub currency_code: ::std::option::Option<::std::string::String>,
    /// Lists tax components applied to the cancellation fee. Typically includes GST or VAT in
    /// markets where such taxes are applicable. Multiple taxes may apply to a fee.
    pub taxes: ::std::option::Option<::std::vec::Vec<Tax>>,
}
