// @generated by openapi-codegen from specs/sabre-booking/spec.openapi.yaml
// Do not edit by hand.

use ::serde::{Deserialize, Serialize};
use ::struct_patch::Patch;
use super::super::shared::common::*;
use super::super::shared::enums::*;
use super::super::shared::request::*;

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);

    impl ::std::error::Error for ConversionError {}

    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }

    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }

    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }

    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}

///Contains a set of additional features whose usage requires explicit indication to maintain backward compatibility. These functionalities will be seamlessly incorporated into a future major version of this API.
#[serde_with::skip_serializing_none]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Patch)]
#[serde(rename_all = "camelCase")]
#[patch(attribute(serde_with::skip_serializing_none))]
#[patch(attribute(derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)))]
#[patch(attribute(serde(default, rename_all = "camelCase")))]
#[cfg_attr(feature = "schemars", patch(attribute(derive(schemars::JsonSchema))))]
pub struct ExtraFeatures {
    #[serde(flatten)]
    pub common_extra_features: CommonExtraFeatures,
    ///If `true`, a lack of seat assignation to the corresponding traveler is marked as an empty `Seat` object. If `false`, empty objects are replaced with null values. Applies to NDC content only.
    pub return_empty_seat_objects: ::std::option::Option<bool>,
}

///Contains both required and optional elements to make a booking request.
#[serde_with::skip_serializing_none]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Patch)]
#[serde(rename_all = "camelCase")]
#[patch(attribute(serde_with::skip_serializing_none))]
#[patch(attribute(derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)))]
#[patch(attribute(serde(default, rename_all = "camelCase")))]
#[cfg_attr(feature = "schemars", patch(attribute(derive(schemars::JsonSchema))))]
pub struct GetBookingRequest {
    pub booking_source: ::std::option::Option<BookingSourceEnum>,
    ///The booking reference ID as shown in the source supplier/vendor system. For `SABRE`, this is the PNR Locator value.
    pub confirmation_id: ::std::string::String,
    #[patch(name = "Option<ExtraFeaturesPatch>")]
    pub extra_features: ::std::option::Option<ExtraFeatures>,
    ///The traveler's first name.
    pub given_name: ::std::option::Option<::std::string::String>,
    ///The middle name or the initial of the middle name of the traveler.
    pub middle_name: ::std::option::Option<::std::string::String>,
    ///Lists the response sections which are returned by the service. If this list is empty or not provided, then the full structure is returned. By using this option, the application may exclude or simplify calls of downline APIs, which usually results in a significant performance boost.
    pub return_only: ::std::option::Option<::std::vec::Vec<ReturnOnlyEnum>>,
    ///The traveler's last name.
    pub surname: ::std::option::Option<::std::string::String>,
    ///The pseudo city code of the target destination in which the booking retrieval is requested.
    pub target_pcc: ::std::option::Option<::std::string::String>,
    ///If true, the application unmasks payment card information stored in the booking. To display this data, the Employee Profile Record (EPR) needs to include the CCVIEW keyword.
    pub unmask_payment_card_numbers: ::std::option::Option<bool>,
}

///Identifies the portion of data to be returned.
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum ReturnOnlyEnum {
    #[serde(rename = "FLIGHTS")]
    Flights,
    #[serde(rename = "FLIGHT_PENALTY")]
    FlightPenalty,
    #[serde(rename = "BAGGAGE_POLICY")]
    BaggagePolicy,
    #[serde(rename = "JOURNEYS")]
    Journeys,
    #[serde(rename = "HOTELS")]
    Hotels,
    #[serde(rename = "HOTEL_ADDRESS")]
    HotelAddress,
    #[serde(rename = "CARS")]
    Cars,
    #[serde(rename = "CAR_RENTAL_ADDRESS")]
    CarRentalAddress,
    #[serde(rename = "CAR_RENTAL_PENALTY")]
    CarRentalPenalty,
    #[serde(rename = "TRAINS")]
    Trains,
    #[serde(rename = "CRUISES")]
    Cruises,
    #[serde(rename = "ALL_SEGMENTS")]
    AllSegments,
    #[serde(rename = "TRAVELERS")]
    Travelers,
    #[serde(rename = "TICKETS")]
    Tickets,
    #[serde(rename = "PAYMENTS")]
    Payments,
    #[serde(rename = "PENALTIES")]
    Penalties,
    #[serde(rename = "REMARKS")]
    Remarks,
    #[serde(rename = "IS_CANCELABLE")]
    IsCancelable,
    #[serde(rename = "IS_TICKETED")]
    IsTicketed,
    #[serde(rename = "CONTACT_INFO")]
    ContactInfo,
    #[serde(rename = "OTHER_SERVICES")]
    OtherServices,
    #[serde(rename = "SPECIAL_SERVICES")]
    SpecialServices,
    #[serde(rename = "FARES")]
    Fares,
    #[serde(rename = "CREATION_DETAILS")]
    CreationDetails,
    #[serde(rename = "ANCILLARIES")]
    Ancillaries,
    #[serde(rename = "FORMS_OF_PAYMENT")]
    FormsOfPayment,
    #[serde(rename = "RETENTION_DATE")]
    RetentionDate,
    #[serde(rename = "ACCOUNTING_ITEMS")]
    AccountingItems,
    #[serde(rename = "NON_ELECTRONIC_TICKETS")]
    NonElectronicTickets,
    #[serde(rename = "TRAVELERS_EMPLOYERS")]
    TravelersEmployers,
    #[serde(rename = "PROFILES")]
    Profiles,
}

impl ::std::fmt::Display for ReturnOnlyEnum {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Flights => f.write_str("FLIGHTS"),
            Self::FlightPenalty => f.write_str("FLIGHT_PENALTY"),
            Self::BaggagePolicy => f.write_str("BAGGAGE_POLICY"),
            Self::Journeys => f.write_str("JOURNEYS"),
            Self::Hotels => f.write_str("HOTELS"),
            Self::HotelAddress => f.write_str("HOTEL_ADDRESS"),
            Self::Cars => f.write_str("CARS"),
            Self::CarRentalAddress => f.write_str("CAR_RENTAL_ADDRESS"),
            Self::CarRentalPenalty => f.write_str("CAR_RENTAL_PENALTY"),
            Self::Trains => f.write_str("TRAINS"),
            Self::Cruises => f.write_str("CRUISES"),
            Self::AllSegments => f.write_str("ALL_SEGMENTS"),
            Self::Travelers => f.write_str("TRAVELERS"),
            Self::Tickets => f.write_str("TICKETS"),
            Self::Payments => f.write_str("PAYMENTS"),
            Self::Penalties => f.write_str("PENALTIES"),
            Self::Remarks => f.write_str("REMARKS"),
            Self::IsCancelable => f.write_str("IS_CANCELABLE"),
            Self::IsTicketed => f.write_str("IS_TICKETED"),
            Self::ContactInfo => f.write_str("CONTACT_INFO"),
            Self::OtherServices => f.write_str("OTHER_SERVICES"),
            Self::SpecialServices => f.write_str("SPECIAL_SERVICES"),
            Self::Fares => f.write_str("FARES"),
            Self::CreationDetails => f.write_str("CREATION_DETAILS"),
            Self::Ancillaries => f.write_str("ANCILLARIES"),
            Self::FormsOfPayment => f.write_str("FORMS_OF_PAYMENT"),
            Self::RetentionDate => f.write_str("RETENTION_DATE"),
            Self::AccountingItems => f.write_str("ACCOUNTING_ITEMS"),
            Self::NonElectronicTickets => f.write_str("NON_ELECTRONIC_TICKETS"),
            Self::TravelersEmployers => f.write_str("TRAVELERS_EMPLOYERS"),
            Self::Profiles => f.write_str("PROFILES"),
        }
    }
}

impl ::std::str::FromStr for ReturnOnlyEnum {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "FLIGHTS" => Ok(Self::Flights),
            "FLIGHT_PENALTY" => Ok(Self::FlightPenalty),
            "BAGGAGE_POLICY" => Ok(Self::BaggagePolicy),
            "JOURNEYS" => Ok(Self::Journeys),
            "HOTELS" => Ok(Self::Hotels),
            "HOTEL_ADDRESS" => Ok(Self::HotelAddress),
            "CARS" => Ok(Self::Cars),
            "CAR_RENTAL_ADDRESS" => Ok(Self::CarRentalAddress),
            "CAR_RENTAL_PENALTY" => Ok(Self::CarRentalPenalty),
            "TRAINS" => Ok(Self::Trains),
            "CRUISES" => Ok(Self::Cruises),
            "ALL_SEGMENTS" => Ok(Self::AllSegments),
            "TRAVELERS" => Ok(Self::Travelers),
            "TICKETS" => Ok(Self::Tickets),
            "PAYMENTS" => Ok(Self::Payments),
            "PENALTIES" => Ok(Self::Penalties),
            "REMARKS" => Ok(Self::Remarks),
            "IS_CANCELABLE" => Ok(Self::IsCancelable),
            "IS_TICKETED" => Ok(Self::IsTicketed),
            "CONTACT_INFO" => Ok(Self::ContactInfo),
            "OTHER_SERVICES" => Ok(Self::OtherServices),
            "SPECIAL_SERVICES" => Ok(Self::SpecialServices),
            "FARES" => Ok(Self::Fares),
            "CREATION_DETAILS" => Ok(Self::CreationDetails),
            "ANCILLARIES" => Ok(Self::Ancillaries),
            "FORMS_OF_PAYMENT" => Ok(Self::FormsOfPayment),
            "RETENTION_DATE" => Ok(Self::RetentionDate),
            "ACCOUNTING_ITEMS" => Ok(Self::AccountingItems),
            "NON_ELECTRONIC_TICKETS" => Ok(Self::NonElectronicTickets),
            "TRAVELERS_EMPLOYERS" => Ok(Self::TravelersEmployers),
            "PROFILES" => Ok(Self::Profiles),
            _ => Err("invalid value".into()),
        }
    }
}

impl ::std::convert::TryFrom<&str> for ReturnOnlyEnum {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}

impl ::std::convert::TryFrom<&::std::string::String> for ReturnOnlyEnum {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}

impl ::std::convert::TryFrom<::std::string::String> for ReturnOnlyEnum {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}

impl ::std::default::Default for ReturnOnlyEnum {
    fn default() -> Self {
        Self::Flights
    }
}
