// @generated by openapi-codegen from specs/petstore.yaml
// Do not edit by hand.

pub mod create_pet;
pub mod get_pet;
pub mod shared;
/// Shared support items for the generated modules: the
/// conversion error type and the impl-condensing macros, defined
/// once instead of per module. Sibling modules re-export
/// [`error`], so `<module>::error::ConversionError` paths keep
/// resolving.
pub mod support;
