// @generated by openapi-codegen from specs/petstore.yaml
// Do not edit by hand.

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);

    impl ::std::error::Error for ConversionError {}

    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }

    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }

    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }

    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}

/// Implements the wire-format conversions for a string enum:
/// `Display` and `FromStr` over the `Variant => "wire value"`
/// pairs (erring with `self::error::ConversionError`), the
/// `TryFrom<&str>` / `TryFrom<&String>` / `TryFrom<String>`
/// ladder via `FromStr`, and — when a `default = Variant`
/// clause is present — `Default`.
macro_rules! impl_string_enum {
    ($Type:ident { $($variant:ident => $raw:literal),* $(,)? } $(default = $default:ident)?) => {
        impl ::std::fmt::Display for $Type {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                match *self {
                    $(Self::$variant => f.write_str($raw),)*
                }
            }
        }
        impl ::std::str::FromStr for $Type {
            type Err = self::error::ConversionError;
            fn from_str(
                value: &str
            ) -> ::std::result::Result<Self, self::error::ConversionError> {
                match value {
                    $($raw => Ok(Self::$variant),)*
                    _ => Err("invalid value".into()),
                }
            }
        }
        impl ::std::convert::TryFrom<&str> for $Type {
            type Error = self::error::ConversionError;
            fn try_from(
                value: &str
            ) -> ::std::result::Result<Self, self::error::ConversionError> {
                value.parse()
            }
        }
        impl ::std::convert::TryFrom<&::std::string::String> for $Type {
            type Error = self::error::ConversionError;
            fn try_from(
                value: &::std::string::String
            ) -> ::std::result::Result<Self, self::error::ConversionError> {
                value.parse()
            }
        }
        impl ::std::convert::TryFrom<::std::string::String> for $Type {
            type Error = self::error::ConversionError;
            fn try_from(
                value: ::std::string::String
            ) -> ::std::result::Result<Self, self::error::ConversionError> {
                value.parse()
            }
        }
        $(
            impl ::std::default::Default for $Type {
                fn default() -> Self {
                    $Type::$default
                }
            }
        )?
    };
}

pub(crate) use impl_string_enum;
