// @generated by openapi-codegen from specs/sabre-booking/spec.openapi.yaml
// Do not edit by hand.

use ::serde::{Deserialize, Serialize};
use ::struct_patch::Patch;
use super::super::get_booking::request::*;
use super::super::shared::common::*;
use super::super::shared::enums::*;
use super::super::shared::response::*;

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);

    impl ::std::error::Error for ConversionError {}

    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }

    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }

    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }

    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}

/// Contains service response object with booking information.
#[serde_with::skip_serializing_none]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Patch)]
#[serde(rename_all = "camelCase")]
#[patch(attribute(serde_with::skip_serializing_none))]
#[patch(attribute(derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)))]
#[patch(attribute(serde(default, rename_all = "camelCase")))]
#[cfg_attr(feature = "schemars", patch(attribute(derive(schemars::JsonSchema))))]
pub struct GetBookingResponse {
    #[serde(flatten)]
    pub booking: Booking,
    /// The unique ID of the Get Booking response. It is used to verify the state of the booking
    /// during the modification operation. Available only if obtaining the booking state does not
    /// result in any errors.
    pub booking_signature: ::std::option::Option<::std::string::String>,
    /// Lists detailed error information. This array is not displayed in successful responses.
    pub errors: ::std::option::Option<::std::vec::Vec<Error>>,
    #[patch(name = "Option<GetBookingRequestPatch>")]
    pub request: ::std::option::Option<GetBookingRequest>,
    /// Provides the exact point in time when the response was generated. The timestamp is expressed
    /// in UTC and presented in the YYYY-MM-DDTHH:MM:SSZ format.
    pub timestamp: ::std::option::Option<::std::string::String>,
}
