//! Drives the staged pipeline API step by step against the petstore spec,
//! customizing every checkpoint the one-shot builder can't reach: the
//! parsed spec, the operation partition, the typify settings, and the
//! final syn AST.
//!
//! Run with:
//!
//! ```text
//! cargo run --example custom_pipeline
//! ```

use openapi_codegen::{Generator, StyleProfile, render_file};

const SPEC: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/specs/petstore.yaml");

fn main() {
    // Stage 1 — load: spec parsed, patch files + patch_spec_with hooks
    // applied. The document is still vanilla OpenAPI, so arbitrary edits
    // (here: documenting a schema) slot in before anything reads it.
    let mut stage = Generator::new(SPEC)
        .profile(StyleProfile::ApiClient)
        .partition_by_operation(true)
        .load()
        .unwrap();
    stage.spec_mut()["components"]["schemas"]["Dog"]["description"] =
        "A very good dog, Rex-approved.".into();

    // Stage 2 — lower: the operation partition is computed and the spec is
    // lowered to JSON Schema. `Dog` is unreachable from any operation, so
    // the reachability walk parks it in `shared`; this run wants it next
    // to the createPet types instead. The typify settings (pre-populated
    // by the ApiClient profile) are also open — embed each type's JSON
    // schema in its doc comment.
    let mut stage = stage.lower().unwrap();
    let partition = stage.partition_mut().unwrap();
    assert_eq!(partition.by_schema["Dog"], "shared");
    partition
        .by_schema
        .insert("Dog".to_string(), "create_pet".to_string());
    stage.settings_mut().with_schema_in_docs(true);

    // Stage 3 — build types: typify has run; inspect what came out before
    // committing to tokens.
    let stage = stage.build_types().unwrap();
    let names = stage.type_space().definition_rust_names();
    assert!(
        names
            .iter()
            .any(|(schema, rust)| schema == "Dog" && rust == "Dog"),
        "typify should emit a `Dog` type for the Dog schema",
    );

    // Stage 4 — AST: `into_file()` applies the profile's default
    // post-processing (Default impls for untagged-oneOf enums); anything
    // syn can express layers on top.
    let mut file = stage.into_file().unwrap();
    file.items
        .push(syn::parse_quote! { pub const GENERATED_BY: &str = "custom_pipeline"; });

    // Stage 5 — render: same formatting + `// @generated` header as the
    // one-shot `generate_to_string`.
    let out = render_file(&file, SPEC);

    assert!(out.starts_with("// @generated by openapi-codegen from"));

    // The spec edit surfaced as the type's doc comment.
    assert!(out.contains("A very good dog, Rex-approved."));

    // The partition override moved `Dog` out of `shared` into `create_pet`.
    assert!(module_body(&out, "create_pet").contains("pub struct Dog"));
    assert!(!module_body(&out, "shared").contains("pub struct Dog"));

    // The settings tweak embedded JSON schemas in the doc comments
    // (the ApiClient style turns them off; upstream's `<details>` block
    // comes back when re-enabled).
    assert!(out.contains("<details><summary>JSON schema</summary>"));

    // The AST edit landed in the output.
    assert!(out.contains("pub const GENERATED_BY: &str = \"custom_pipeline\";"));

    println!("custom_pipeline example: all assertions passed");
}

/// The body of the top-level `pub mod <name> { ... }` block in `source`.
/// prettyplease emits top-level modules at column 0, so the next
/// unindented `pub mod ` (or end of input) closes the slice; nested
/// modules like `error` / `defaults` are indented and don't match.
fn module_body<'a>(source: &'a str, name: &str) -> &'a str {
    let open = format!("pub mod {name} {{");
    let start = source
        .find(&open)
        .unwrap_or_else(|| panic!("no `pub mod {name}` in output"));
    let rest = &source[start + open.len()..];
    let end = rest.find("\npub mod ").unwrap_or(rest.len());
    &rest[..end]
}
