//! Compiles the full Sabre Booking Management API surface (257 schemas,
//! 9 operations) generated by this crate in folder-tree form — one
//! directory per operation with `request.rs` / `response.rs` leaves,
//! plus `shared/{request,response,enums,common}` — and exercises a
//! request the way the hand-written client types are used.
//!
//! Regenerate with:
//!
//! ```text
//! cargo run -- generate --spec specs/sabre-booking/spec.openapi.yaml \
//!     --patches-dir specs/sabre-booking/patches --profile api-client \
//!     --split-request-response \
//!     --output-dir examples/generated_tree/sabre_booking
//! ```

// Generated modules glob-import each other for cross-module type
// references; with 257 schemas most imports and types go unused here.
// Clippy style lints don't apply to generated code.
#[allow(unused_imports, dead_code, clippy::all)]
#[path = "generated_tree/sabre_booking/mod.rs"]
mod sabre_booking;

use sabre_booking::cancel_booking::request::CancelBookingRequest;
use sabre_booking::shared::common::FlightReference;
use sabre_booking::shared::enums::BookingSourceEnum;
use struct_patch::Patch as _;

fn main() {
    // The request type lives in its operation's `request` module; the
    // enum comes from `shared::enums` and the multi-role reference type
    // from `shared::common` — the same split the hand-written
    // sabre-types crate uses.
    let request = CancelBookingRequest {
        confirmation_id: "GLEBNY".to_string(),
        booking_source: Some(BookingSourceEnum::Sabre),
        retrieve_booking: Some(true),
        cancel_all: Some(true),
        flights: Some(vec![FlightReference {
            item_id: "12".to_string(),
        }]),
        ..Default::default()
    };

    let wire = serde_json::to_value(&request).unwrap();
    assert_eq!(
        wire,
        serde_json::json!({
            "confirmationId": "GLEBNY",
            "bookingSource": "SABRE",
            "retrieveBooking": true,
            "cancelAll": true,
            "flights": [ { "itemId": "12" } ],
        }),
    );

    // Round-trip: the wire JSON deserializes back into the same value.
    let round_tripped: CancelBookingRequest = serde_json::from_value(wire).unwrap();
    assert_eq!(round_tripped, request);

    // Partial updates parse straight into the generated `*Patch` type.
    let patch = serde_json::from_value(serde_json::json!({
        "cancelAll": false,
        "receivedFrom": "Agent",
    }))
    .unwrap();
    let mut patched = request.clone();
    patched.apply(patch);
    assert_eq!(patched.cancel_all, Some(false));
    assert_eq!(patched.received_from.as_deref(), Some("Agent"));
    assert_eq!(patched.confirmation_id, "GLEBNY");

    println!("sabre_booking_tree example: all assertions passed");
}
