//! Compiles the full Sabre Booking Management API surface (257 schemas,
//! 9 operations) generated by this crate, and exercises a request the way
//! the hand-written client types are used.
//!
//! Regenerate with:
//!
//! ```text
//! cargo run -- generate --spec specs/sabre-booking/spec.openapi.yaml \
//!     --patches-dir specs/sabre-booking/patches --profile api-client \
//!     --partition-by-operation --output examples/generated/sabre_booking.rs
//! ```

// Generated modules glob-import each other for cross-module type
// references; with 257 schemas most imports and types go unused here.
// Clippy style lints don't apply to generated code.
#[allow(unused_imports, dead_code, clippy::all)]
#[path = "generated/sabre_booking.rs"]
mod sabre_booking;

use sabre_booking::cancel_booking::CancelBookingRequest;
use sabre_booking::shared::{BookingSourceEnum, FlightReference};
use struct_patch::Patch as _;

fn main() {
    let request = CancelBookingRequest {
        confirmation_id: "GLEBNY".to_string(),
        booking_source: Some(BookingSourceEnum::Sabre),
        retrieve_booking: Some(true),
        cancel_all: Some(true),
        flights: Some(vec![FlightReference {
            item_id: "12".to_string(),
        }]),
        ..Default::default()
    };

    let wire = serde_json::to_value(&request).unwrap();
    assert_eq!(
        wire,
        serde_json::json!({
            "confirmationId": "GLEBNY",
            "bookingSource": "SABRE",
            "retrieveBooking": true,
            "cancelAll": true,
            "flights": [ { "itemId": "12" } ],
        }),
    );

    // Partial updates parse straight into the generated `*Patch` type.
    let patch = serde_json::from_value(serde_json::json!({
        "cancelAll": false,
        "receivedFrom": "Agent",
    }))
    .unwrap();
    let mut patched = request.clone();
    patched.apply(patch);
    assert_eq!(patched.cancel_all, Some(false));
    assert_eq!(patched.received_from.as_deref(), Some("Agent"));
    assert_eq!(patched.confirmation_id, "GLEBNY");

    println!("sabre_booking example: all assertions passed");
}
