// @generated by openapi-codegen from specs/sabre-booking/spec.openapi.yaml
// Do not edit by hand.

use super::support::{Error, OperationInfo};

/// Authorizes outgoing requests.
///
/// The client calls [`AuthProvider::authorize`] with every request builder before the body is
/// attached; implementations add whatever credentials the API expects. Custom providers (e.g.
/// from the `ext` module) can implement this trait to change auth behavior without touching
/// generated code.
#[::async_trait::async_trait]
pub trait AuthProvider: ::std::marker::Send + ::std::marker::Sync {
    /// Attach credentials to `request`. `op` identifies the
    /// operation being sent, so providers can specialize.
    async fn authorize(
        &self,
        request: ::reqwest_middleware::RequestBuilder,
        op: &OperationInfo,
    ) -> ::std::result::Result<::reqwest_middleware::RequestBuilder, Error>;
}

/// No authentication: requests pass through untouched. The
/// builder default.
#[derive(Debug, Clone, Copy, Default)]
pub struct NoAuth;

#[::async_trait::async_trait]
impl AuthProvider for NoAuth {
    async fn authorize(
        &self,
        request: ::reqwest_middleware::RequestBuilder,
        _op: &OperationInfo,
    ) -> ::std::result::Result<::reqwest_middleware::RequestBuilder, Error> {
        ::std::result::Result::Ok(request)
    }
}

/// A fixed token attached as `Authorization: Bearer <token>` on
/// every request.
#[derive(Clone)]
pub struct StaticBearer {
    token: ::std::string::String,
}

impl StaticBearer {
    pub fn new(token: impl ::std::convert::Into<::std::string::String>) -> Self {
        Self { token: token.into() }
    }
}

#[::async_trait::async_trait]
impl AuthProvider for StaticBearer {
    async fn authorize(
        &self,
        request: ::reqwest_middleware::RequestBuilder,
        _op: &OperationInfo,
    ) -> ::std::result::Result<::reqwest_middleware::RequestBuilder, Error> {
        ::std::result::Result::Ok(request.bearer_auth(&self.token))
    }
}

/// OAuth2 client-credentials flow with a TTL token cache, generated from the
/// `oauth2_authentication` security scheme.
///
/// Fetches `POST https://api.cert.platform.sabre.com/v2/auth/token` with
/// `grant_type=client_credentials` and a `Basic` header carrying the client credentials, caches
/// the returned token until `expires_in` elapses, and attaches it to API requests as a bearer
/// token.
///
/// Per the scheme's `x-base64-encode-client-credentials: true`, the id and secret are
/// individually base64-encoded before the standard `base64(id:secret)` basic-auth encoding.
pub struct OAuth2ClientCredentials {
    token_url: ::std::string::String,
    client_id: ::std::string::String,
    client_secret: ::std::string::String,
    base64_encode_client_credentials: bool,
    http: ::reqwest::Client,
    token: ::std::sync::Mutex<::std::option::Option<CachedToken>>,
}

#[derive(Clone)]
struct CachedToken {
    access_token: ::std::string::String,
    obtained_at: ::std::time::Instant,
    ttl: ::std::time::Duration,
}

#[derive(::serde::Deserialize)]
struct TokenResponse {
    access_token: ::std::string::String,
    /// Token lifetime in seconds; when the endpoint omits it,
    /// the token is used but not cached.
    #[serde(default)]
    expires_in: ::std::option::Option<u64>,
}

impl OAuth2ClientCredentials {
    /// The spec's token endpoint
    /// (`securitySchemes.oauth2_authentication.flows.clientCredentials.tokenUrl`).
    pub const DEFAULT_TOKEN_URL: &'static str = "https://api.cert.platform.sabre.com/v2/auth/token";

    /// A provider with the spec defaults: [`Self::DEFAULT_TOKEN_URL`],
    /// the spec's credential encoding, and a fresh plain
    /// `reqwest::Client` for token fetches.
    pub fn new(
        client_id: impl ::std::convert::Into<::std::string::String>,
        client_secret: impl ::std::convert::Into<::std::string::String>,
    ) -> Self {
        Self {
            token_url: Self::DEFAULT_TOKEN_URL.to_string(),
            client_id: client_id.into(),
            client_secret: client_secret.into(),
            base64_encode_client_credentials: true,
            http: ::reqwest::Client::new(),
            token: ::std::sync::Mutex::new(::std::option::Option::None),
        }
    }

    /// Override the token endpoint.
    pub fn token_url(
        mut self,
        token_url: impl ::std::convert::Into<::std::string::String>,
    ) -> Self {
        self.token_url = token_url.into();
        self
    }

    /// Override the credential encoding: when `true`, the id and
    /// secret are individually base64-encoded before the standard
    /// basic-auth encoding.
    pub fn base64_encode_client_credentials(mut self, enabled: bool) -> Self {
        self.base64_encode_client_credentials = enabled;
        self
    }

    /// Override the HTTP client used for token fetches.
    pub fn http_client(mut self, client: ::reqwest::Client) -> Self {
        self.http = client;
        self
    }

    /// The `Basic ...` header value for the token request.
    fn credentials_header(&self) -> ::std::string::String {
        use ::base64::Engine as _;
        let engine = ::base64::engine::general_purpose::STANDARD;
        let credentials = if self.base64_encode_client_credentials {
            let id = engine.encode(&self.client_id);
            let secret = engine.encode(&self.client_secret);
            ::std::format!("{id}:{secret}")
        } else {
            ::std::format!("{}:{}", self.client_id, self.client_secret)
        };
        let encoded = engine.encode(credentials);
        ::std::format!("Basic {encoded}")
    }

    /// The cached access token, refreshed when missing or expired.
    ///
    /// Lock discipline: lock, check, clone, drop — the mutex guard is never held across an await.
    /// Two callers racing an expired token may both fetch; each stores a valid token and the last
    /// store wins, so the duplicate fetch is accepted rather than serializing every call through
    /// the cache.
    async fn access_token(
        &self,
        op: &OperationInfo,
    ) -> ::std::result::Result<::std::string::String, Error> {
        {
            let guard = self
                .token
                .lock()
                .unwrap_or_else(::std::sync::PoisonError::into_inner);
            if let ::std::option::Option::Some(cached) = guard.as_ref()
                && cached.obtained_at.elapsed() < cached.ttl
            {
                return ::std::result::Result::Ok(cached.access_token.clone());
            }
        }
        let fetched = self.fetch_token(op).await?;
        if let ::std::option::Option::Some(expires_in) = fetched.expires_in {
            let mut guard = self
                .token
                .lock()
                .unwrap_or_else(::std::sync::PoisonError::into_inner);
            *guard = ::std::option::Option::Some(CachedToken {
                access_token: fetched.access_token.clone(),
                obtained_at: ::std::time::Instant::now(),
                ttl: ::std::time::Duration::from_secs(expires_in),
            });
        }
        ::std::result::Result::Ok(fetched.access_token)
    }

    /// One `grant_type=client_credentials` POST to the token
    /// endpoint. Failures surface as [`Error::Auth`] naming the
    /// operation that needed the token.
    async fn fetch_token(
        &self,
        op: &OperationInfo,
    ) -> ::std::result::Result<TokenResponse, Error> {
        let response = self
            .http
            .post(&self.token_url)
            .header(::reqwest::header::AUTHORIZATION, self.credentials_header())
            .form(&[("grant_type", "client_credentials")])
            .send()
            .await
            .map_err(|source| Error::Auth {
                op: op.operation_id,
                message: ::std::format!("token request failed: {source}"),
            })?;
        let status = response.status();
        let body = response
            .text()
            .await
            .map_err(|source| Error::Auth {
                op: op.operation_id,
                message: ::std::format!("token response read failed: {source}"),
            })?;
        if !status.is_success() {
            return ::std::result::Result::Err(Error::Auth {
                op: op.operation_id,
                message: ::std::format!("token endpoint answered {status}: {body}"),
            });
        }
        ::serde_json::from_str(&body)
            .map_err(|source| Error::Auth {
                op: op.operation_id,
                message: ::std::format!(
                    "token response decode failed: {source} (line {line}, column {column}); raw body: {body}",
                    line = source.line(), column = source.column(),
                ),
            })
    }
}

#[::async_trait::async_trait]
impl AuthProvider for OAuth2ClientCredentials {
    async fn authorize(
        &self,
        request: ::reqwest_middleware::RequestBuilder,
        op: &OperationInfo,
    ) -> ::std::result::Result<::reqwest_middleware::RequestBuilder, Error> {
        let token = self.access_token(op).await?;
        ::std::result::Result::Ok(request.bearer_auth(token))
    }
}
