// @generated by openapi-codegen from specs/sabre-booking/spec.openapi.yaml
// Do not edit by hand.

pub mod auth;
pub mod support;

use self::auth::AuthProvider;
use self::support::{BodyHook, Error, OperationInfo};

/// Client for Booking Management API (v1.32).
///
/// Construct via [`Client::builder`]; the base URL defaults to the spec's first server,
/// `https://api.cert.platform.sabre.com/v1/trip/orders`.
#[derive(Clone)]
pub struct Client {
    base_url: ::std::string::String,
    client: ::reqwest_middleware::ClientWithMiddleware,
    auth: ::std::sync::Arc<dyn AuthProvider>,
    body_hooks: ::std::vec::Vec<::std::sync::Arc<BodyHook>>,
}

impl ::std::fmt::Debug for Client {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.debug_struct("Client")
            .field("base_url", &self.base_url)
            .finish_non_exhaustive()
    }
}

/// Builder for [`Client`].
pub struct ClientBuilder {
    base_url: ::std::string::String,
    client: ::std::option::Option<::reqwest_middleware::ClientWithMiddleware>,
    auth: ::std::sync::Arc<dyn AuthProvider>,
    body_hooks: ::std::vec::Vec<::std::sync::Arc<BodyHook>>,
}

impl ClientBuilder {
    /// Start a builder with the spec's default base URL,
    /// `https://api.cert.platform.sabre.com/v1/trip/orders`.
    pub fn new() -> Self {
        Self {
            base_url: "https://api.cert.platform.sabre.com/v1/trip/orders".to_string(),
            client: ::std::option::Option::None,
            auth: ::std::sync::Arc::new(auth::NoAuth),
            body_hooks: ::std::vec::Vec::new(),
        }
    }

    /// Override the base URL operation paths are appended
    /// to. A trailing `/` is trimmed at build time.
    pub fn base_url(
        mut self,
        base_url: impl ::std::convert::Into<::std::string::String>,
    ) -> Self {
        self.base_url = base_url.into();
        self
    }

    /// Supply the HTTP client requests are sent through: a
    /// `reqwest_middleware::ClientWithMiddleware` carrying a middleware stack, or a plain
    /// `reqwest::Client` (converted middleware-free via `From`). Defaults to a fresh plain client.
    pub fn client(
        mut self,
        client: impl ::std::convert::Into<::reqwest_middleware::ClientWithMiddleware>,
    ) -> Self {
        self.client = ::std::option::Option::Some(client.into());
        self
    }

    /// Set the authentication provider; see [`auth`] for the
    /// generated implementations. Defaults to
    /// [`auth::NoAuth`].
    pub fn auth(mut self, auth: impl AuthProvider + 'static) -> Self {
        self.auth = ::std::sync::Arc::new(auth);
        self
    }

    /// Register a request-body hook: after a request body is serialized to JSON and before it is
    /// sent, every hook runs against the `serde_json::Value` in registration order. The seam for
    /// cross-cutting request edits (inject a tenant field, fill a default) without forking
    /// generated code; `OperationInfo` tells the hook which operation is sending.
    pub fn body_hook(
        mut self,
        hook: impl ::std::ops::Fn(
            &OperationInfo,
            &mut ::serde_json::Value,
        ) + ::std::marker::Send + ::std::marker::Sync + 'static,
    ) -> Self {
        self.body_hooks.push(::std::sync::Arc::new(hook));
        self
    }

    pub fn build(self) -> Client {
        Client {
            base_url: self.base_url.trim_end_matches('/').to_string(),
            client: self.client.unwrap_or_else(|| ::reqwest::Client::new().into()),
            auth: self.auth,
            body_hooks: self.body_hooks,
        }
    }
}

impl ::std::default::Default for ClientBuilder {
    fn default() -> Self {
        Self::new()
    }
}

impl Client {
    /// Start building a client; see [`ClientBuilder`].
    pub fn builder() -> ClientBuilder {
        ClientBuilder::new()
    }

    /// The configured base URL (trailing `/` trimmed).
    pub fn base_url(&self) -> &str {
        &self.base_url
    }

    /// Cancels a booking or specified booking items, optionally voiding or refunding related flight
    /// tickets.
    ///
    /// `POST /cancelBooking`
    pub async fn cancel_booking(
        &self,
        body: &super::cancel_booking::request::CancelBookingRequest,
    ) -> ::std::result::Result<
        super::cancel_booking::response::CancelBookingResponse,
        Error,
    > {
        const OP: OperationInfo = OperationInfo {
            operation_id: "cancelBooking",
            method: "POST",
            path: "/cancelBooking",
        };
        let url = ::std::format!("{}/cancelBooking", self.base_url);
        let mut request = self.client.request(::reqwest::Method::POST, url);
        request = self.auth.authorize(request, &OP).await?;
        let mut body = ::serde_json::to_value(body)
            .map_err(|source| Error::Serialize {
                op: OP.operation_id,
                source,
            })?;
        for hook in &self.body_hooks {
            hook(&OP, &mut body);
        }
        request = request.json(&body);
        let response = request
            .send()
            .await
            .map_err(|source| Error::Request {
                op: OP.operation_id,
                source,
            })?;
        support::decode_json(OP.operation_id, response).await
    }

    /// Checks tickets with ticket numbers listed in the request for void, refund and exchange
    /// conditions. EMDs are currently not supported.
    ///
    /// `POST /checkFlightTickets`
    pub async fn check_tickets(
        &self,
        body: &super::check_tickets::request::CheckTicketsRequest,
    ) -> ::std::result::Result<
        super::check_tickets::response::CheckTicketsResponse,
        Error,
    > {
        const OP: OperationInfo = OperationInfo {
            operation_id: "checkTickets",
            method: "POST",
            path: "/checkFlightTickets",
        };
        let url = ::std::format!("{}/checkFlightTickets", self.base_url);
        let mut request = self.client.request(::reqwest::Method::POST, url);
        request = self.auth.authorize(request, &OP).await?;
        let mut body = ::serde_json::to_value(body)
            .map_err(|source| Error::Serialize {
                op: OP.operation_id,
                source,
            })?;
        for hook in &self.body_hooks {
            hook(&OP, &mut body);
        }
        request = request.json(&body);
        let response = request
            .send()
            .await
            .map_err(|source| Error::Request {
                op: OP.operation_id,
                source,
            })?;
        support::decode_json(OP.operation_id, response).await
    }

    /// Creates an air booking (NDC/ATPCO/LCC).
    ///
    /// `POST /createBooking`
    pub async fn create_booking(
        &self,
        body: &super::create_booking::request::CreateBookingRequest,
    ) -> ::std::result::Result<
        super::create_booking::response::CreateBookingResponse,
        Error,
    > {
        const OP: OperationInfo = OperationInfo {
            operation_id: "createBooking",
            method: "POST",
            path: "/createBooking",
        };
        let url = ::std::format!("{}/createBooking", self.base_url);
        let mut request = self.client.request(::reqwest::Method::POST, url);
        request = self.auth.authorize(request, &OP).await?;
        let mut body = ::serde_json::to_value(body)
            .map_err(|source| Error::Serialize {
                op: OP.operation_id,
                source,
            })?;
        for hook in &self.body_hooks {
            hook(&OP, &mut body);
        }
        request = request.json(&body);
        let response = request
            .send()
            .await
            .map_err(|source| Error::Request {
                op: OP.operation_id,
                source,
            })?;
        support::decode_json(OP.operation_id, response).await
    }

    /// Processes the fulfillment of flight tickets (for ATPCO and NDC content) and Electronic
    /// Miscellaneous Documents (EMDs).
    ///
    /// `POST /fulfillFlightTickets`
    pub async fn fulfill_tickets(
        &self,
        body: &super::fulfill_tickets::request::FulfillTicketsRequest,
    ) -> ::std::result::Result<
        super::fulfill_tickets::response::FulfillTicketsResponse,
        Error,
    > {
        const OP: OperationInfo = OperationInfo {
            operation_id: "fulfillTickets",
            method: "POST",
            path: "/fulfillFlightTickets",
        };
        let url = ::std::format!("{}/fulfillFlightTickets", self.base_url);
        let mut request = self.client.request(::reqwest::Method::POST, url);
        request = self.auth.authorize(request, &OP).await?;
        let mut body = ::serde_json::to_value(body)
            .map_err(|source| Error::Serialize {
                op: OP.operation_id,
                source,
            })?;
        for hook in &self.body_hooks {
            hook(&OP, &mut body);
        }
        request = request.json(&body);
        let response = request
            .send()
            .await
            .map_err(|source| Error::Request {
                op: OP.operation_id,
                source,
            })?;
        support::decode_json(OP.operation_id, response).await
    }

    /// Displays comprehensive booking details irrespective of source, optionally narrowing down the
    /// response to selected elements.
    ///
    /// `POST /getBooking`
    pub async fn get_booking(
        &self,
        body: &super::get_booking::request::GetBookingRequest,
    ) -> ::std::result::Result<super::get_booking::response::GetBookingResponse, Error> {
        const OP: OperationInfo = OperationInfo {
            operation_id: "getBooking",
            method: "POST",
            path: "/getBooking",
        };
        let url = ::std::format!("{}/getBooking", self.base_url);
        let mut request = self.client.request(::reqwest::Method::POST, url);
        request = self.auth.authorize(request, &OP).await?;
        let mut body = ::serde_json::to_value(body)
            .map_err(|source| Error::Serialize {
                op: OP.operation_id,
                source,
            })?;
        for hook in &self.body_hooks {
            hook(&OP, &mut body);
        }
        request = request.json(&body);
        let response = request
            .send()
            .await
            .map_err(|source| Error::Request {
                op: OP.operation_id,
                source,
            })?;
        support::decode_json(OP.operation_id, response).await
    }

    /// Creates a list of booking items that need to be modified.
    ///
    /// `POST /modifyBooking`
    pub async fn modify_booking(
        &self,
        body: &super::modify_booking::request::ModifyBookingRequest,
    ) -> ::std::result::Result<
        super::modify_booking::response::ModifyBookingResponse,
        Error,
    > {
        const OP: OperationInfo = OperationInfo {
            operation_id: "modifyBooking",
            method: "POST",
            path: "/modifyBooking",
        };
        let url = ::std::format!("{}/modifyBooking", self.base_url);
        let mut request = self.client.request(::reqwest::Method::POST, url);
        request = self.auth.authorize(request, &OP).await?;
        let mut body = ::serde_json::to_value(body)
            .map_err(|source| Error::Serialize {
                op: OP.operation_id,
                source,
            })?;
        for hook in &self.body_hooks {
            hook(&OP, &mut body);
        }
        request = request.json(&body);
        let response = request
            .send()
            .await
            .map_err(|source| Error::Request {
                op: OP.operation_id,
                source,
            })?;
        support::decode_json(OP.operation_id, response).await
    }

    /// Processes documents by providing a request containing a list of tickets or/and EMDs which
    /// should be refunded.
    ///
    /// `POST /refundFlightTickets`
    pub async fn refund_tickets(
        &self,
        body: &super::refund_tickets::request::RefundTicketsRequest,
    ) -> ::std::result::Result<
        super::refund_tickets::response::RefundTicketsResponse,
        Error,
    > {
        const OP: OperationInfo = OperationInfo {
            operation_id: "refundTickets",
            method: "POST",
            path: "/refundFlightTickets",
        };
        let url = ::std::format!("{}/refundFlightTickets", self.base_url);
        let mut request = self.client.request(::reqwest::Method::POST, url);
        request = self.auth.authorize(request, &OP).await?;
        let mut body = ::serde_json::to_value(body)
            .map_err(|source| Error::Serialize {
                op: OP.operation_id,
                source,
            })?;
        for hook in &self.body_hooks {
            hook(&OP, &mut body);
        }
        request = request.json(&body);
        let response = request
            .send()
            .await
            .map_err(|source| Error::Request {
                op: OP.operation_id,
                source,
            })?;
        support::decode_json(OP.operation_id, response).await
    }

    /// Voids tickets with ticket numbers listed in the request, optionally including nonelectronic
    /// tickets (paper).
    ///
    /// `POST /voidFlightTickets`
    pub async fn void_tickets(
        &self,
        body: &super::void_tickets::request::VoidTicketsRequest,
    ) -> ::std::result::Result<
        super::void_tickets::response::VoidTicketsResponse,
        Error,
    > {
        const OP: OperationInfo = OperationInfo {
            operation_id: "voidTickets",
            method: "POST",
            path: "/voidFlightTickets",
        };
        let url = ::std::format!("{}/voidFlightTickets", self.base_url);
        let mut request = self.client.request(::reqwest::Method::POST, url);
        request = self.auth.authorize(request, &OP).await?;
        let mut body = ::serde_json::to_value(body)
            .map_err(|source| Error::Serialize {
                op: OP.operation_id,
                source,
            })?;
        for hook in &self.body_hooks {
            hook(&OP, &mut body);
        }
        request = request.json(&body);
        let response = request
            .send()
            .await
            .map_err(|source| Error::Request {
                op: OP.operation_id,
                source,
            })?;
        support::decode_json(OP.operation_id, response).await
    }
}
