// @generated by openapi-codegen from specs/petstore.yaml
// Do not edit by hand.

use ::serde::{Deserialize, Serialize};
use ::struct_patch::Patch;
use super::super::support::impl_string_enum;
pub use super::super::support::error;

/// `PetStatus`
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum PetStatus {
    #[serde(rename = "available")]
    Available,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "sold")]
    Sold,
}

impl_string_enum!(PetStatus {
    Available => "available",
    Pending => "pending",
    Sold => "sold",
} default = Available);
