// @generated by openapi-codegen from specs/petstore.yaml
// Do not edit by hand.

use ::serde::{Deserialize, Serialize};
use ::struct_patch::Patch;
use super::super::shared::common::*;
use super::super::shared::enums::*;
pub use super::super::support::error;
