// @generated by openapi-codegen from specs/petstore.yaml
// Do not edit by hand.

use ::serde::{Deserialize, Serialize};
use ::struct_patch::Patch;
use super::super::shared::common::*;
use super::super::shared::enums::*;
pub use super::super::support::error;

///`Pet`
#[serde_with::skip_serializing_none]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Patch)]
#[serde(rename_all = "camelCase")]
#[patch(attribute(serde_with::skip_serializing_none))]
#[patch(attribute(derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)))]
#[patch(attribute(serde(default, rename_all = "camelCase")))]
#[cfg_attr(feature = "schemars", patch(attribute(derive(schemars::JsonSchema))))]
pub struct Pet {
    #[patch(name = "Option<CategoryPatch>")]
    pub category: ::std::option::Option<Category>,
    pub created_at: ::std::option::Option<::std::string::String>,
    pub id: ::std::string::String,
    pub name: ::std::string::String,
    pub status: ::std::option::Option<PetStatus>,
    pub tag_count: ::std::option::Option<i32>,
}
