// @generated by openapi-codegen from specs/sabre-booking/spec.openapi.yaml
// Do not edit by hand.

use ::serde::{Deserialize, Serialize};
use ::struct_patch::Patch;
use super::super::shared::common::*;
use super::super::shared::enums::*;
use super::super::shared::request::*;

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);

    impl ::std::error::Error for ConversionError {}

    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }

    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }

    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }

    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}

///Contains required and optional elements to void tickets.
#[serde_with::skip_serializing_none]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, Patch)]
#[serde(rename_all = "camelCase")]
#[patch(attribute(serde_with::skip_serializing_none))]
#[patch(attribute(derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)))]
#[patch(attribute(serde(default, rename_all = "camelCase")))]
#[cfg_attr(feature = "schemars", patch(attribute(derive(schemars::JsonSchema))))]
pub struct VoidTicketsRequest {
    ///The booking reference ID as shown in the source supplier or vendor system.
    pub confirmation_id: ::std::option::Option<::std::string::String>,
    ///Lists printers or a printer profile to designate. It is possible to provide a single `PrinterAddress` object with a printer profile. Alternatively, the array may contain multiple `PrinterAddress` objects, but each of them must have the same printer type definition.
    pub designate_printers: ::std::option::Option<::std::vec::Vec<PrinterAddress>>,
    pub error_handling_policy: ::std::option::Option<CancelErrorPolicyEnum>,
    #[patch(name = "Option<NotificationPatch>")]
    pub notification: ::std::option::Option<Notification>,
    ///The entity that authorizes the changes in a Passenger Name Record.
    pub received_from: ::std::option::Option<::std::string::String>,
    ///The pseudo city code of the target destination for which the ticket voiding is requested.
    pub target_pcc: ::std::option::Option<::std::string::String>,
    ///Lists document numbers for tickets or EMDs which should be voided. Can contain up to 12 elements.
    pub tickets: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    ///If `true`, nonelectronic tickets are included in the void process.
    pub void_non_electronic_tickets: ::std::option::Option<bool>,
}
